# $Id$

CC = $(PTHREAD_CC)
CFLAGS += -std=gnu99 -Wall -Wextra
CPPFLAGS += $(PTHREAD_CFLAGS) -D_POSIX_PTHREAD_SEMANTICS
CPPFLAGS += -I$(top_srcdir)/libsauth/include -I$(top_srcdir)/common
LDFLAGS += $(PTHREAD_LIBS)
