# $Id$

CC = $(PTHREAD_CC)
AM_CFLAGS = -std=gnu99 -Wall -Wextra $(PTHREAD_CFLAGS)
AM_CPPFLAGS = -D_POSIX_PTHREAD_SEMANTICS
AM_CPPFLAGS += -I$(top_srcdir)/libsauth/include -I$(top_srcdir)/common
AM_LDFLAGS = $(PTHREAD_LIBS)
